version: 0.2

env:
  variables:
    HOME: "/tmp" # Đặt biến môi trường HOME

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing dependencies
      - composer install
  build:
    commands:
      - echo Build completed
      - ls -la
      - php -v
artifacts:
  files:
    - '**/*'
  discard-paths: no
