version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing dependencies
      - composer install
  build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
  discard-paths: no
